/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.ModeloTabela;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Misael
 */
public class TelaSimpson extends javax.swing.JFrame {

//    declarando variaveis
    double limite_superior, limite_inferior, h;

    /**
     * Creates new form TelaSimpson
     */
    public TelaSimpson() {
        initComponents();
//        PreencherTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSimpson = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbh = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_n = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Método de Simpson", 0, 0, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        tabelaSimpson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tabelaSimpson);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("y =");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("a =");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("b =");

        txt_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("h =");

        lbh.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lbh.setText("valor de incremento h");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("n =");

        txt_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nActionPerformed(evt);
            }
        });

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_a))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_n)))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(lbh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_n, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(787, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
//        PreencherTabela();
        double b = Double.parseDouble(txt_b.getText());
        double a = Double.parseDouble(txt_a.getText());
        
        if (txt_b.getText().equals("") || txt_a.getText().equals("") || txt_n.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Os Campos b , a e n nao deve, ser nulos");
        } else {

            if (b <=a) {
                JOptionPane.showMessageDialog(null, "b>a");

            } else {
//                h = (limite_superior - limite_inferior) / Integer.parseInt(txt_n.getText());
//                lbh.setText("" + h);
            }
        }


    }//GEN-LAST:event_btn_calcularActionPerformed

    private void txt_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nActionPerformed

    private void txt_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSimpson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSimpson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSimpson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSimpson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSimpson().setVisible(true);
            }
        });
    }

    public void PreencherTabela() {

        for (int i = 0; i <= Integer.parseInt(txt_n.getText()); i++) {

            ArrayList dados = new ArrayList();
            String[] colunas = new String[]{"i", "X=x +i*h", "F(x)"};

            ModeloTabela modelo = new ModeloTabela(dados, colunas);
            tabelaSimpson.setModel(modelo);
            this.tabelaSimpson.getColumnModel().getColumn(0).setPreferredWidth(100);
            this.tabelaSimpson.getColumnModel().getColumn(1).setPreferredWidth(100);
            this.tabelaSimpson.getColumnModel().getColumn(2).setPreferredWidth(100);

            this.tabelaSimpson.getColumnModel().getColumn(0).setResizable(false);
            this.tabelaSimpson.getColumnModel().getColumn(1).setResizable(false);
            this.tabelaSimpson.getColumnModel().getColumn(2).setResizable(false);

            this.tabelaSimpson.getTableHeader().setReorderingAllowed(false);
            this.tabelaSimpson.setAutoResizeMode(tabelaSimpson.AUTO_RESIZE_ALL_COLUMNS);
            this.tabelaSimpson.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        }

        int n = Integer.parseInt(txt_n.getText());

        double pa = limite_inferior;
        double x = 1;
        double f1 = 0, fn = 0, fi;

        double funcao_par = 1, funcao_impar = 1;

        h = (limite_superior - limite_inferior) / n;

        // 4 impares e 2 pares
        double soma_par = 0, soma_impar = 0, soma_extremos = 0;

        System.out.println("h= " + h);

        ArrayList lista = new ArrayList<Object>();

        for (int i = 0; i <= n; i++) {
            if (i == 0) {
                pa = pa;
            } else {
                pa = pa + h;
            }

            // System.out.println(i); quando FOR pAR
            if ((i != 0) && (i != n) && ((i % 2) == 0)) {
                System.out.println("I  Par = " + i);
                funcao_par = pa * pa;
                soma_par = soma_par + funcao_par;
                System.out.println("Valor de Cada Funcao Par:" + funcao_par);
                System.out.println("F" + i + " = " + funcao_par);
                lista.add(funcao_par);

            } else {
                // Quando FOR IMPAR
                if ((i != 0) && (i != n)) {
                    System.out.println("I  Impar = " + i);
                    funcao_impar = pa * pa;
                    soma_impar = soma_impar + funcao_impar;

                    System.out.println("Valor de Cada Funcao ImPar:" + funcao_impar);
                    System.out.println("F" + i + " = " + funcao_impar);

                    lista.add(funcao_impar);
                } else {
                    double fo = pa * pa;
                    soma_extremos = soma_extremos + fo;

                    System.out.println("indice" + i);
                    System.out.println("F" + i + " = " + fo + "\n");
                    lista.add(fo);
                }

            }

        }

//        System.out.println("h = " + h);
//        System.out.println("Soma De Valores Pares: " + soma_par);
//        System.out.println("Soma De Extremos: " + soma_extremos);
//        System.out.println("Soma De Valores Impares: " + soma_impar + "\n");
//
//        double formula = (h / 3) * (soma_extremos + 4 * soma_impar + 2 * soma_par);
//
//        System.out.println("Area da Figura= " + formula);
        for (int i = 0; i < lista.size(); i++) {
            System.out.println("Valor" + i + ":" + lista.get(i).toString() + "\n");
        }
//        Por Resultado Na Tabela
        try {

            for (int i = 0; i < lista.size(); i++) {

                // dados.add(new Object[]{lista.get(i)});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro ao listar: " + e.getMessage());
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbh;
    private javax.swing.JTable tabelaSimpson;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_n;
    // End of variables declaration//GEN-END:variables
}
